### PR TITLE
#58 #28 issues Fixed 

### LINKED ISSUE #58: Make Utility Class or Function to except illegal input
Now, we make the function of null or NaN input exception .
We should make some utility class or function to except illegal input.

illegal input: null, NaN, undefined, "", "       ", 0, false, [ ], { }

### PR DESCRIPTION
**Pull request by ShimizuKazuki**
#58 and #28 issues are fixed.
It changed all function's empty check, and add function of getting spot by coordinate(x , y)

### CODE REVIEW

File: back/src/database/ReviewSQL.js [hunk 1]
```diff
@@ -6,6 +6,8 @@ const pool = con.pool;
 const fileLabel = "ReviewSQL"
 const Review = require('../objects/review');
 const util = require('util');
+const utility = require('../utility');
+const { isEmpty } = require('../utility');
```
Comment (ONourry) [inline back/src/database/ReviewSQL.js]: Why do you need both line 9 and 10? Only one seems fine

File: back/src/database/SpotSQL.js [hunk 2]
```diff
@@ -20,53 +21,44 @@ async function saveSpot(newSpot){
...
+        error(fileLabel,"Spot Name is invalid");
+        return {"success":false,"data":"Spot Name is invalid"};
+    } else if(utility.isEmpty(newSpot.spotType)){
+        error(fileLabel,"ERROR OBJECT:" + util.inspect(newSpot.spotName,{showHidden: false, depth: null}));
+        error(fileLabel,"Spot Type is invalid");
+        return {"success":false,"data":"Spot Type is invalid"};
+    }
+
     const client = await pool.connect();
     //TODO: NULL CHECK
```
Comment (ONourry) [inline back/src/database/SpotSQL.js]: Don't need this line anymore. You're doing the NULL/Undefined check with the isEmpty function

File: back/src/database/ReviewSQL.js [hunk 3]
```diff
@@ -16,19 +17,18 @@ module.exports.saveReview = async function(newReview){
...
-            info(fileLabel,"ERROR OBJECT:" + util.inspect(newReview.spotId,{showHidden: false, depth: null}));
-            error(fileLabel,"Spot Id is Undefined" + newReview.spotId);
-            return {"success":false,"data":"Spot Id is Undefined"};
-        }else if(nullchecker.rowCount == 0){
+         if(nullchecker.rowCount == 0){
             client.release();
-            info(fileLabel,"ERROR OBJECT:" + util.inspect(newReview.spotId,{showHidden: false, depth: null}));
-            error(fileLabel,"There is no spot at: " + newReview.spotId);
-            return {"success":false,"data":newReview.spotId};
+            return {"success":false,"data":"This spot does no exist: " + newSpot.spotName};
```
Comment (kyamatek) [inline back/src/database/ReviewSQL.js]: no -> not

**Review by kyamatek — APPROVED** [review]

**Review by Asada0815 — APPROVED** [review]

**Review by matsuoharuki — APPROVED** [review]

**Review by tsukasa2 — APPROVED** [review]
